### ISSUE TITLE
Please add an option to disable autorun

### ISSUE THREAD

**Issue by aelmahmoudy** [rtreffer/ContactMerger#1]
ContactsMerger runs the analysis a lot on my phone. Please add an option that enables the user to only run  the analyze function manually.

**Comment by rtreffer** [comment]
Hi,

I wanted to heavily increase the wanted interval (7d if you are charging and your battery is >95%) and going as much as 3 months without a scan...

I'm also adding a cancel option if it still fires off at the wrong time.

Would that suit you?

**Comment by aelmahmoudy** [comment]
That would be nice

**Comment by rtreffer** [comment]
I have just pushed the required changes. I'll do a release the next time I'm at home :-)

On 27. Juli 2014 15:41:54 MESZ, "أحمد المحمودي" notifications@github.com wrote:

> That would be nice
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rtreffer/ContactMerger/issues/1#issuecomment-50264626

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rtreffer** [comment]
There is still one bug: the notification does not go away if I stop the scan, release after that fix. Besides that everything looks good.

**Comment by rtreffer** [comment]
Scan can now be aborted, version is tagged and released. (There is a minor flickering if you abort)

Please open a new issue if you have any other complaints.

**Comment by aelmahmoudy** [comment]
Thanks. Tried it today from F-Droid, and I was able to manually start/stop the analyze functionality !
